proc RandomBlockPlacer(){
    //Input
	int $sizePlus = 10;
	int $sizeMinus = 1;
	int $blocksAmnt = 10;
	//Work
    for ($i = 1; $i < $blocksAmnt; $i++ ){
	float $randNumOne = `rand $sizeMinus $sizePlus`;
	float $randNumTwo = `rand $sizeMinus $sizePlus`;
	float $randNumThree = `rand $sizeMinus $sizePlus`;
	string $objs[];

	$objs = `polyCube`;
	move -absolute -worldSpace ($randNumOne) ($randNumTwo) ($randNumThree) $objs[0];
    }
  }
RandomBlockPlacer();
